import AsyncStorage from "@react-native-async-storage/async-storage";
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";
import { translations as baseTranslations } from "@constants/translations";

const SUPPORTED_LANGUAGES = ["fr", "en", "ar", "tr"];
const FALLBACK_LANGUAGE = "fr";
const LANGUAGE_STORAGE_KEY = "userLanguage";

export const LANGUAGE_OPTIONS = [
  { code: "fr", short: "FR", label: "Francais" },
  { code: "en", short: "EN", label: "English" },
  { code: "ar", short: "AR", label: "Arabic" },
  { code: "tr", short: "TR", label: "Turkish" },
];

const AUTH_TRANSLATIONS = {
  fr: {
    tabs: { login: "Se connecter", signup: "S'inscrire", admin: "Admin" },
    common: {
      confirm: "Confirmer",
      errorTitle: "Erreur",
      successTitle: "Succes",
      error: "Erreur",
      success: "Succes",
      loading: "Chargement...",
      googleLogin: "Connexion avec Google",
    },
    login: {
      emailLabel: "Entrer l'adresse e-mail",
      emailPlaceholder: "Votre adresse e-mail",
      passwordLabel: "Mot de passe",
      forgotPassword: "Mot de passe oublie ?",
      loginLoading: "Connexion...",
      noAccount: "Vous n'avez pas de compte ?",
      invalidCredentials: "Identifiants incorrects.",
      invalidEmail: "Veuillez entrer une adresse e-mail valide.",
      fillFields: "Veuillez remplir tous les champs.",
    },
    admin: {
      title: "Espace administrateur",
      subtitle: "Connectez-vous pour gerer SmartIrrig.",
      emailLabel: "Email administrateur",
      emailPlaceholder: "admin@smartirrig.com",
      passwordLabel: "Mot de passe",
      loginLoading: "Connexion admin...",
      accessButton: "Acceder",
      invalidCredentials: "Identifiants administrateur incorrects.",
      fillFields: "Veuillez remplir tous les champs.",
      dashboardTitle: "Tableau de bord",
      dashboardSubtitle: "Bienvenue dans votre panneau d'administration SmartIrrig",
      totalClients: "Total clients",
      activeUsers: "Utilisateurs actifs",
      activeRate: "actifs",
      waterSaved: "Eau irriguee",
      growth: "Croissance",
      thisMonth: "ce mois-ci",
      monthOverMonth: "mois sur mois",
      clientList: "Liste des clients",
      searchPlaceholder: "Rechercher...",
      newClient: "Nouveau client",
      actions: "Actions",
      status: "Statut",
      name: "Nom",
      active: "Actif",
      inactive: "Inactif",
      noClients: "Aucun client trouve",
      featureSoon: "Fonctionnalite bientot disponible.",
      navDashboard: "Dashboard",
      navCultures: "Cultures",
      navIrrigations: "Irrigations",
      navUsers: "Utilisateurs",
      navMessages: "Messages",
      messagesTitle: "Messages",
      messagesAll: "Tous",
      messagesUnread: "Non lus",
      messagesAllSubtitle: "Tous les messages recus",
      messagesUnreadSubtitle: "Messages non lus",
      messagesEmptyTitle: "Aucun message",
      messagesEmptySubtitle: "Les messages des utilisateurs apparaitront ici.",
      messageDetails: "Details",
      messageFrom: "De",
      messageEmail: "Email",
      messageWhen: "Quand",
      messageSubject: "Objet",
      messageBody: "Message",
      markingRead: "Marquage comme lu...",
      manager: "Gestionnaire",
      cardCultures: "Cultures",
      cardIrrigations: "Irrigations",
      cardVolumeTotal: "Volume total",
      cardTotalSurface: "Surface totale",
      cardTotalUsers: "Total utilisateurs",
      cardActiveUsers: "Actifs",
      cardTotalDuration: "Duree totale",
      recentIrrigations: "Irrigations recentes",
      noIrrigationsToday: "Aucune irrigation aujourd'hui",
      irrigationsCount: "session(s)",
      results: "resultat(s)",
      volumeByMode: "Volume par mode",
      chartVolumeTitle: "Volume irrigue",
      lastDays: "derniers jours",
      culturesList: "Cultures",
      irrigationsList: "Irrigations",
      usersList: "Utilisateurs",
      search: "Rechercher...",
      add: "Ajouter",
      filterAllModes: "Tous les modes",
      tableCulture: "Culture",
      tableParcel: "Parcelle",
      tableSurface: "Surface",
      tableStage: "Stade",
      tablePlanting: "Plantation",
      tableMode: "Mode",
      tableVolume: "Volume",
      tableDuration: "Duree",
      tableEtc: "ETC",
      tableKc: "Kc",
      tableName: "Nom",
      tableEmail: "Email",
      tableStatus: "Statut",
      emptyCultures: "Aucune culture trouvee",
      emptyIrrigations: "Aucune irrigation trouvee",
      emptyUsers: "Aucun utilisateur trouve",
      tableActions: "Actions",
      deleteUserTitle: "Supprimer utilisateur",
      deleteUserConfirm: "Voulez-vous vraiment supprimer cet utilisateur ?",
      deleteUserSuccess: "Utilisateur supprime.",
      totalCultures: "Total cultures",
      totalSurface: "Surface totale",
      totalIrrigations: "Total irrigations",
      totalVolume: "Volume total",
      totalDuration: "Duree totale",
      totalUsers: "Total utilisateurs",
    },
    drawer: {
      roleAdmin: "Administrateur",
      roleUser: "Utilisateur",
      guest: "Utilisateur",
      languageTitle: "Langue",
      signOut: "Se deconnecter",
      tagline: "Gestion intelligente de l'irrigation",
    },
    messages: {
      contactTitle: "Contacter l'admin",
      writeToAdmin: "Ecrire a l'administrateur",
      subtitle: "Envoyez un message a l'administrateur. Il verra votre nom, votre email et la date d'envoi.",
      unknownUser: "Utilisateur",
      subject: "Objet (optionnel)",
      subjectPlaceholder: "Ex: Probleme de connexion",
      message: "Message",
      messagePlaceholder: "Decrivez votre demande...",
      send: "Envoyer",
      sending: "Envoi...",
      sentTitle: "Message envoye",
      sentBody: "Votre message a ete envoye a l'administrateur.",
      tooShort: "Votre message est trop court.",
      hint: "Votre message est enregistre et visible par l'administrateur.",
    },
    signup: {
      firstNameLabel: "Votre prenom",
      firstNamePlaceholder: "Entrez votre prenom...",
      lastNameLabel: "Votre nom",
      lastNamePlaceholder: "Entrez votre nom...",
      addressLabel: "Votre adresse",
      addressPlaceholder: "Entrez votre adresse...",
      emailLabel: "Entrer l'adresse e-mail",
      emailPlaceholder: "Votre adresse e-mail",
      passwordLabel: "Creer un mot de passe",
      signupLoading: "Inscription...",
      createdMessage: "Compte cree. Vous pouvez vous connecter.",
      signupFailed: "Inscription echouee.",
      invalidEmail: "Veuillez entrer une adresse e-mail valide.",
      passwordTooShort: "Le mot de passe doit contenir au moins 8 caracteres.",
      firstNameTooShort: "Le prenom doit contenir au moins 2 caracteres.",
      lastNameTooShort: "Le nom doit contenir au moins 2 caracteres.",
      addressTooShort: "L'adresse doit contenir au moins 5 caracteres.",
      fillFields: "Veuillez remplir tous les champs.",
    },
    forgotPassword: {
      emailLabel: "Entrer l'adresse e-mail",
      emailPlaceholder: "Votre adresse e-mail",
      emailRequired: "Veuillez entrer votre adresse e-mail.",
      submitLoading: "Envoi...",
      unexpectedError: "Une erreur est survenue.",
    },
    confirmCode: {
      title: "Entrer le code de confirmation",
      emailMissing: "Adresse e-mail introuvable.",
      codeIncomplete: "Veuillez entrer le code complet.",
      invalidCode: "Code invalide.",
      submitLoading: "Verification...",
    },
    newPassword: {
      title: "Nouveau mot de passe",
      createPassword: "Creer un mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      missingValidation: "Informations de validation manquantes.",
      fillFields: "Veuillez remplir tous les champs.",
      mismatch: "Les mots de passe ne correspondent pas.",
      minLength: "Le mot de passe doit contenir au moins 8 caracteres.",
      submitLoading: "Enregistrement...",
      unexpectedError: "Une erreur est survenue.",
    },
    passwordSuccess: {
      title: "Felicitations !",
      line1: "Votre mot de passe a ete change.",
      line2: "Cliquez sur Continuer pour vous connecter.",
      continue: "Continuer",
    },
    authHome: {
      title: "Bienvenue",
      subtitle: "Vous etes connecte. Ceci est l'ecran d'accueil.",
      logout: "Se deconnecter",
    },
  },
  en: {
    tabs: { login: "Log in", signup: "Sign up", admin: "Admin" },
    common: {
      confirm: "Confirm",
      errorTitle: "Error",
      successTitle: "Success",
      error: "Error",
      success: "Success",
      loading: "Loading...",
      googleLogin: "Continue with Google",
    },
    login: {
      emailLabel: "Email address",
      emailPlaceholder: "Your email address",
      passwordLabel: "Password",
      forgotPassword: "Forgot password?",
      loginLoading: "Signing in...",
      noAccount: "Don't have an account?",
      invalidCredentials: "Incorrect credentials.",
      invalidEmail: "Please enter a valid email address.",
      fillFields: "Please fill in all fields.",
    },
    admin: {
      title: "Admin access",
      subtitle: "Sign in to manage SmartIrrig.",
      emailLabel: "Admin email",
      emailPlaceholder: "admin@smartirrig.com",
      passwordLabel: "Password",
      loginLoading: "Signing in...",
      accessButton: "Access",
      invalidCredentials: "Invalid admin credentials.",
      fillFields: "Please fill in all fields.",
      dashboardTitle: "Dashboard",
      dashboardSubtitle: "Welcome to your SmartIrrig admin panel",
      totalClients: "Total clients",
      activeUsers: "Active users",
      activeRate: "active",
      waterSaved: "Water managed",
      growth: "Growth",
      thisMonth: "this month",
      monthOverMonth: "month over month",
      clientList: "Client list",
      searchPlaceholder: "Search...",
      newClient: "New client",
      actions: "Actions",
      status: "Status",
      name: "Name",
      active: "Active",
      inactive: "Inactive",
      noClients: "No clients found",
      featureSoon: "Feature coming soon.",
      navDashboard: "Dashboard",
      navCultures: "Cultures",
      navIrrigations: "Irrigations",
      navUsers: "Users",
      navMessages: "Messages",
      messagesTitle: "Messages",
      messagesAll: "All",
      messagesUnread: "Unread",
      messagesAllSubtitle: "All received messages",
      messagesUnreadSubtitle: "Unread messages",
      messagesEmptyTitle: "No messages",
      messagesEmptySubtitle: "User messages will appear here.",
      messageDetails: "Details",
      messageFrom: "From",
      messageEmail: "Email",
      messageWhen: "When",
      messageSubject: "Subject",
      messageBody: "Message",
      markingRead: "Marking as read...",
      manager: "Manager",
      cardCultures: "Cultures",
      cardIrrigations: "Irrigations",
      cardVolumeTotal: "Total volume",
      cardTotalSurface: "Total area",
      cardTotalUsers: "Total users",
      cardActiveUsers: "Active",
      cardTotalDuration: "Total duration",
      recentIrrigations: "Recent irrigations",
      noIrrigationsToday: "No irrigation today",
      irrigationsCount: "session(s)",
      results: "result(s)",
      volumeByMode: "Volume by mode",
      chartVolumeTitle: "Irrigated volume",
      lastDays: "last days",
      culturesList: "Cultures",
      irrigationsList: "Irrigations",
      usersList: "Users",
      search: "Search...",
      add: "Add",
      filterAllModes: "All modes",
      tableCulture: "Culture",
      tableParcel: "Parcel",
      tableSurface: "Area",
      tableStage: "Stage",
      tablePlanting: "Planting",
      tableMode: "Mode",
      tableVolume: "Volume",
      tableDuration: "Duration",
      tableEtc: "ETC",
      tableKc: "Kc",
      tableName: "Name",
      tableEmail: "Email",
      tableStatus: "Status",
      emptyCultures: "No cultures found",
      emptyIrrigations: "No irrigations found",
      emptyUsers: "No users found",
      tableActions: "Actions",
      deleteUserTitle: "Delete user",
      deleteUserConfirm: "Are you sure you want to delete this user?",
      deleteUserSuccess: "User deleted.",
      totalCultures: "Total cultures",
      totalSurface: "Total area",
      totalIrrigations: "Total irrigations",
      totalVolume: "Total volume",
      totalDuration: "Total duration",
      totalUsers: "Total users",
    },
    drawer: {
      roleAdmin: "Administrator",
      roleUser: "User",
      guest: "User",
      languageTitle: "Language",
      signOut: "Sign out",
      tagline: "Smart irrigation management",
    },
    messages: {
      contactTitle: "Contact admin",
      writeToAdmin: "Write to the administrator",
      subtitle: "Send a message to the administrator. They will see your name, email, and sent date.",
      unknownUser: "User",
      subject: "Subject (optional)",
      subjectPlaceholder: "e.g. Login issue",
      message: "Message",
      messagePlaceholder: "Describe your request...",
      send: "Send",
      sending: "Sending...",
      sentTitle: "Message sent",
      sentBody: "Your message has been sent to the administrator.",
      tooShort: "Your message is too short.",
      hint: "Your message is saved and visible to the administrator.",
    },
    signup: {
      firstNameLabel: "First name",
      firstNamePlaceholder: "Enter first name...",
      lastNameLabel: "Last name",
      lastNamePlaceholder: "Enter last name...",
      addressLabel: "Address",
      addressPlaceholder: "Enter address...",
      emailLabel: "Email address",
      emailPlaceholder: "Your email address",
      passwordLabel: "Create password",
      signupLoading: "Creating account...",
      createdMessage: "Account created. You can sign in now.",
      signupFailed: "Sign up failed.",
      invalidEmail: "Please enter a valid email address.",
      passwordTooShort: "Password must be at least 8 characters.",
      firstNameTooShort: "First name must be at least 2 characters.",
      lastNameTooShort: "Last name must be at least 2 characters.",
      addressTooShort: "Address must be at least 5 characters.",
      fillFields: "Please fill in all fields.",
    },
    forgotPassword: {
      emailLabel: "Email address",
      emailPlaceholder: "Your email address",
      emailRequired: "Please enter your email address.",
      submitLoading: "Sending...",
      unexpectedError: "Unexpected error.",
    },
    confirmCode: {
      title: "Enter confirmation code",
      emailMissing: "Email not found.",
      codeIncomplete: "Please enter full code.",
      invalidCode: "Invalid code.",
      submitLoading: "Verifying...",
    },
    newPassword: {
      title: "New password",
      createPassword: "Create password",
      confirmPassword: "Confirm password",
      missingValidation: "Missing validation data.",
      fillFields: "Please fill in all fields.",
      mismatch: "Passwords do not match.",
      minLength: "Password must be at least 8 characters.",
      submitLoading: "Saving...",
      unexpectedError: "Unexpected error.",
    },
    passwordSuccess: {
      title: "Great!",
      line1: "Your password has been changed.",
      line2: "Tap continue to sign in.",
      continue: "Continue",
    },
    authHome: {
      title: "Welcome",
      subtitle: "You are connected. This is the home screen.",
      logout: "Log out",
    },
  },
  ar: {
    tabs: { login: "تسجيل الدخول", signup: "إنشاء حساب" },
    common: {
      confirm: "تأكيد",
      errorTitle: "خطأ",
      successTitle: "نجاح",
      error: "خطأ",
      success: "نجاح",
      loading: "جارٍ التحميل...",
      googleLogin: "المتابعة مع Google",
    },
    login: {
      emailLabel: "البريد الإلكتروني",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      passwordLabel: "كلمة المرور",
      forgotPassword: "هل نسيت كلمة المرور؟",
      loginLoading: "جاري تسجيل الدخول...",
      noAccount: "ليس لديك حساب؟",
      invalidCredentials: "بيانات الدخول غير صحيحة.",
      invalidEmail: "يرجى إدخال بريد إلكتروني صالح.",
      fillFields: "يرجى ملء جميع الحقول.",
    },
    admin: {
      navDashboard: "لوحة التحكم",
      navCultures: "المحاصيل",
      navIrrigations: "الري",
      navUsers: "المستخدمون",
      navMessages: "الرسائل",
      messagesTitle: "الرسائل",
      messagesAll: "الكل",
      messagesUnread: "غير مقروءة",
      messagesAllSubtitle: "جميع الرسائل المستلمة",
      messagesUnreadSubtitle: "الرسائل غير المقروءة",
      messagesEmptyTitle: "لا توجد رسائل",
      messagesEmptySubtitle: "ستظهر رسائل المستخدمين هنا.",
      messageDetails: "التفاصيل",
      messageFrom: "من",
      messageEmail: "البريد",
      messageWhen: "الوقت",
      messageSubject: "الموضوع",
      messageBody: "الرسالة",
      markingRead: "جارٍ وضع علامة مقروء...",
      manager: "مدير",
      cardCultures: "المحاصيل",
      cardIrrigations: "الري",
      cardVolumeTotal: "الحجم الإجمالي",
      cardTotalSurface: "المساحة الإجمالية",
      cardTotalUsers: "إجمالي المستخدمين",
      cardActiveUsers: "النشطون",
      cardTotalDuration: "المدة الإجمالية",
      recentIrrigations: "أحدث عمليات الري",
      noIrrigationsToday: "لا توجد عمليات ري اليوم",
      irrigationsCount: "جلسة",
      results: "نتائج",
      volumeByMode: "الحجم حسب النظام",
      chartVolumeTitle: "حجم الري",
      lastDays: "الأيام الأخيرة",
      culturesList: "المحاصيل",
      irrigationsList: "الري",
      usersList: "المستخدمون",
      search: "بحث...",
      add: "إضافة",
      filterAllModes: "جميع الأنظمة",
      tableCulture: "المحصول",
      tableParcel: "القطعة",
      tableSurface: "المساحة",
      tableStage: "المرحلة",
      tablePlanting: "الزراعة",
      tableMode: "النظام",
      tableVolume: "الحجم",
      tableDuration: "المدة",
      tableEtc: "ETc",
      tableKc: "Kc",
      tableName: "الاسم",
      tableEmail: "البريد",
      tableStatus: "الحالة",
      emptyCultures: "لا توجد محاصيل",
      emptyIrrigations: "لا توجد عمليات ري",
      emptyUsers: "لا يوجد مستخدمون",
      tableActions: "إجراءات",
      deleteUserTitle: "حذف مستخدم",
      deleteUserConfirm: "هل تريد حذف هذا المستخدم؟",
      deleteUserSuccess: "تم حذف المستخدم.",
      totalCultures: "إجمالي المحاصيل",
      totalSurface: "المساحة الإجمالية",
      totalIrrigations: "إجمالي الري",
      totalVolume: "الحجم الإجمالي",
      totalDuration: "المدة الإجمالية",
      totalUsers: "إجمالي المستخدمين",
      usersTitle: "إدارة المستخدمين",
      userTotal: "الإجمالي",
      userActive: "النشطون",
      userInactive: "غير النشطين",
      userNew: "جديد",
      userSearch: "بحث...",
      userCount: "مستخدم",
      colName: "الاسم",
      colEmail: "البريد",
      colStatus: "الحالة",
      colActions: "إجراءات",
      userActive_label: "نشط",
      userInactive_label: "غير نشط",
      userNone: "لا يوجد مستخدمون",
      userCreate: "مستخدم جديد",
      userEdit: "تعديل المستخدم",
      userEmailReadonly: "البريد الإلكتروني غير قابل للتعديل",
      userFieldLastName: "اسم العائلة",
      userFieldFirstName: "الاسم الأول",
      userFieldAddress: "العنوان",
      userFieldEmail: "البريد الإلكتروني",
      userFieldPassword: "كلمة المرور",
      userPasswordOptional: "اتركه فارغاً = بدون تغيير",
      userPasswordNew: "كلمة مرور جديدة...",
      userPasswordMin: "الحد الأدنى 8 أحرف",
      userAccountActive: "حساب نشط",
      userAccountActiveDesc: "يمكن للمستخدم تسجيل الدخول",
      userAccountInactiveDesc: "الحساب معطل",
      userSaveCreate: "إنشاء المستخدم",
      userSaveEdit: "حفظ التعديلات",
      userFullName: "الاسم الكامل",
      userAddress: "العنوان",
      userRegistered: "تاريخ التسجيل",
      userAccountStatus: "حالة الحساب",
      userStatusActive: "نشط — يمكنه تسجيل الدخول",
      userStatusInactive: "معطل — الوصول محظور",
      userDeactivate: "تعطيل",
      userActivate: "تفعيل",
      userTabProfile: "الملف الشخصي",
      userTabCultures: "المحاصيل",
      userNoCultures: "لا توجد محاصيل",
      userNoCulturesDesc: "لم يضف هذا المستخدم أي محاصيل بعد",
      userDeleteTitle: "حذف المستخدم",
      userDeleteConfirm: "تأكيد الحذف؟",
      userDeleteIrreversible: "هذا الإجراء لا يمكن التراجع عنه.",
      userDeleteBtn: "حذف",
      userCancelBtn: "إلغاء",
      userCreatedSuccess: "تم إنشاء المستخدم بنجاح.",
      userUpdatedSuccess: "تم تعديل المستخدم بنجاح.",
      userDeletedSuccess: "تم الحذف بنجاح.",
      userLoadError: "تعذر التحميل",
      userStatusError: "تعذر تغيير الحالة",
      userDeleteError: "فشل الحذف.",
      userErrFirstName: "الاسم الأول مطلوب.",
      userErrLastName: "اسم العائلة مطلوب.",
      userErrEmail: "البريد الإلكتروني غير صحيح.",
      userErrPassword: "كلمة المرور 8 أحرف على الأقل.",
      userErrServer: "خطأ في الخادم.",
    },
    signup: {
      firstNameLabel: "الاسم الأول",
      firstNamePlaceholder: "أدخل الاسم الأول...",
      lastNameLabel: "اسم العائلة",
      lastNamePlaceholder: "أدخل اسم العائلة...",
      addressLabel: "العنوان",
      addressPlaceholder: "أدخل العنوان...",
      emailLabel: "البريد الإلكتروني",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      passwordLabel: "إنشاء كلمة المرور",
      signupLoading: "جاري إنشاء الحساب...",
      createdMessage: "تم إنشاء الحساب. يمكنك تسجيل الدخول الآن.",
      signupFailed: "فشل إنشاء الحساب.",
      invalidEmail: "يرجى إدخال بريد إلكتروني صالح.",
      passwordTooShort: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
      firstNameTooShort: "يجب أن يكون الاسم الأول حرفين على الأقل.",
      lastNameTooShort: "يجب أن يكون اسم العائلة حرفين على الأقل.",
      addressTooShort: "يجب أن يكون العنوان 5 أحرف على الأقل.",
      fillFields: "يرجى ملء جميع الحقول.",
    },
    forgotPassword: {
      emailLabel: "البريد الإلكتروني",
      emailPlaceholder: "أدخل بريدك الإلكتروني",
      emailRequired: "يرجى إدخال البريد الإلكتروني.",
      submitLoading: "جاري الإرسال...",
      unexpectedError: "حدث خطأ غير متوقع.",
    },
    confirmCode: {
      title: "أدخل رمز التأكيد",
      emailMissing: "البريد الإلكتروني غير موجود.",
      codeIncomplete: "يرجى إدخال الرمز كاملا.",
      invalidCode: "رمز غير صالح.",
      submitLoading: "جاري التحقق...",
    },
    newPassword: {
      title: "كلمة مرور جديدة",
      createPassword: "إنشاء كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      missingValidation: "بيانات التحقق مفقودة.",
      fillFields: "يرجى ملء جميع الحقول.",
      mismatch: "كلمتا المرور غير متطابقتين.",
      minLength: "يجب أن تكون كلمة المرور 8 أحرف على الأقل.",
      submitLoading: "جاري الحفظ...",
      unexpectedError: "حدث خطأ غير متوقع.",
    },
    passwordSuccess: {
      title: "ممتاز!",
      line1: "تم تغيير كلمة المرور بنجاح.",
      line2: "اضغط متابعة لتسجيل الدخول.",
      continue: "متابعة",
    },
    authHome: {
      title: "مرحبا",
      subtitle: "تم تسجيل الدخول. هذه هي الشاشة الرئيسية.",
      logout: "تسجيل الخروج",
    },
    messages: {
      contactTitle: "مراسلة المسؤول",
      writeToAdmin: "اكتب إلى المسؤول",
      subtitle: "أرسل رسالة إلى المسؤول. سيشاهد اسمك وبريدك وتاريخ الإرسال.",
      unknownUser: "مستخدم",
      subject: "الموضوع (اختياري)",
      subjectPlaceholder: "مثال: مشكلة تسجيل الدخول",
      message: "الرسالة",
      messagePlaceholder: "اكتب رسالتك هنا...",
      send: "إرسال",
      sending: "جارٍ الإرسال...",
      sentTitle: "تم الإرسال",
      sentBody: "تم إرسال رسالتك إلى المسؤول.",
      tooShort: "رسالتك قصيرة جدًا.",
      hint: "يتم حفظ رسالتك ويمكن للمسؤول رؤيتها.",
    },
    drawer: {
      roleAdmin: "مسؤول",
      roleUser: "مستخدم",
      guest: "مستخدم",
      languageTitle: "اللغة",
      signOut: "تسجيل الخروج",
      tagline: "إدارة ذكية للري",
    },
  },
  tr: {
    tabs: { login: "Giris", signup: "Kayit ol" },
    common: {
      confirm: "Onayla",
      errorTitle: "Hata",
      successTitle: "Basarili",
      error: "Hata",
      success: "Basarili",
      loading: "Yukleniyor...",
      googleLogin: "Google ile devam et",
    },
    login: {
      emailLabel: "E-posta adresi",
      emailPlaceholder: "E-posta adresiniz",
      passwordLabel: "Sifre",
      forgotPassword: "Sifremi unuttum?",
      loginLoading: "Giris yapiliyor...",
      noAccount: "Hesabin yok mu?",
      invalidCredentials: "Kimlik bilgileri hatali.",
      invalidEmail: "Gecerli bir e-posta adresi girin.",
      fillFields: "Lutfen tum alanlari doldurun.",
    },
    admin: {
      navDashboard: "Kontrol Paneli",
      navCultures: "Kulturler",
      navIrrigations: "Sulamalar",
      navUsers: "Kullanicilar",
      navMessages: "Mesajlar",
      messagesTitle: "Mesajlar",
      messagesAll: "Tum",
      messagesUnread: "Okunmamis",
      messagesAllSubtitle: "Tum gelen mesajlar",
      messagesUnreadSubtitle: "Okunmamis mesajlar",
      messagesEmptyTitle: "Mesaj yok",
      messagesEmptySubtitle: "Kullanici mesajlari burada gorunecek.",
      messageDetails: "Detaylar",
      messageFrom: "Gonderen",
      messageEmail: "E-posta",
      messageWhen: "Zaman",
      messageSubject: "Konu",
      messageBody: "Mesaj",
      markingRead: "Okundu olarak isaretleniyor...",
      manager: "Yonetici",
      cardCultures: "Kulturler",
      cardIrrigations: "Sulamalar",
      cardVolumeTotal: "Toplam hacim",
      cardTotalSurface: "Toplam alan",
      cardTotalUsers: "Toplam kullanici",
      cardActiveUsers: "Aktif",
      cardTotalDuration: "Toplam sure",
      recentIrrigations: "Son sulamalar",
      noIrrigationsToday: "Bugun sulama yok",
      irrigationsCount: "oturum",
      results: "sonuc",
      volumeByMode: "Moda gore hacim",
      chartVolumeTitle: "Sulama hacmi",
      lastDays: "son gun",
      culturesList: "Kulturler",
      irrigationsList: "Sulamalar",
      usersList: "Kullanicilar",
      search: "Ara...",
      add: "Ekle",
      filterAllModes: "Tum modlar",
      tableCulture: "Kultur",
      tableParcel: "Parsel",
      tableSurface: "Alan",
      tableStage: "Evre",
      tablePlanting: "Dikim",
      tableMode: "Mod",
      tableVolume: "Hacim",
      tableDuration: "Sure",
      tableEtc: "ETC",
      tableKc: "Kc",
      tableName: "Ad",
      tableEmail: "E-posta",
      tableStatus: "Durum",
      emptyCultures: "Kultur bulunamadi",
      emptyIrrigations: "Sulama bulunamadi",
      emptyUsers: "Kullanici bulunamadi",
      tableActions: "Islemler",
      deleteUserTitle: "Kullanici sil",
      deleteUserConfirm: "Bu kullaniciyi silmek istiyor musunuz?",
      deleteUserSuccess: "Kullanici silindi.",
      totalCultures: "Toplam kultur",
      totalSurface: "Toplam alan",
      totalIrrigations: "Toplam sulama",
      totalVolume: "Toplam hacim",
      totalDuration: "Toplam sure",
      totalUsers: "Toplam kullanici",
    },
    signup: {
      firstNameLabel: "Ad",
      firstNamePlaceholder: "Adinizi girin...",
      lastNameLabel: "Soyad",
      lastNamePlaceholder: "Soyadinizi girin...",
      addressLabel: "Adres",
      addressPlaceholder: "Adresinizi girin...",
      emailLabel: "E-posta adresi",
      emailPlaceholder: "E-posta adresiniz",
      passwordLabel: "Sifre olustur",
      signupLoading: "Hesap olusturuluyor...",
      createdMessage: "Hesap olusturuldu. Giris yapabilirsiniz.",
      signupFailed: "Kayit basarisiz.",
      invalidEmail: "Gecerli bir e-posta adresi girin.",
      passwordTooShort: "Sifre en az 8 karakter olmalidir.",
      firstNameTooShort: "Ad en az 2 karakter olmalidir.",
      lastNameTooShort: "Soyad en az 2 karakter olmalidir.",
      addressTooShort: "Adres en az 5 karakter olmalidir.",
      fillFields: "Lutfen tum alanlari doldurun.",
    },
    forgotPassword: {
      emailLabel: "E-posta adresi",
      emailPlaceholder: "E-posta adresiniz",
      emailRequired: "Lutfen e-posta adresini girin.",
      submitLoading: "Gonderiliyor...",
      unexpectedError: "Beklenmeyen bir hata olustu.",
    },
    confirmCode: {
      title: "Onay kodunu girin",
      emailMissing: "E-posta bulunamadi.",
      codeIncomplete: "Lutfen kodu tamamen girin.",
      invalidCode: "Gecersiz kod.",
      submitLoading: "Dogrulaniyor...",
    },
    newPassword: {
      title: "Yeni sifre",
      createPassword: "Sifre olustur",
      confirmPassword: "Sifreyi onayla",
      missingValidation: "Dogrulama bilgisi eksik.",
      fillFields: "Lutfen tum alanlari doldurun.",
      mismatch: "Sifreler eslesmiyor.",
      minLength: "Sifre en az 8 karakter olmalidir.",
      submitLoading: "Kaydediliyor...",
      unexpectedError: "Beklenmeyen bir hata olustu.",
    },
    passwordSuccess: {
      title: "Harika!",
      line1: "Sifreniz basariyla degistirildi.",
      line2: "Giris yapmak icin Devam'a basin.",
      continue: "Devam",
    },
    authHome: {
      title: "Hos geldiniz",
      subtitle: "Baglandiniz. Bu ana ekrandir.",
      logout: "Cikis yap",
    },
    messages: {
      contactTitle: "Admin iletisim",
      writeToAdmin: "Yoneticiye yaz",
      subtitle: "Yoneticiye mesaj gonderin. Adinizi, e-postanizi ve gonderim tarihini gorecek.",
      unknownUser: "Kullanici",
      subject: "Konu (opsiyonel)",
      subjectPlaceholder: "Orn: Giris sorunu",
      message: "Mesaj",
      messagePlaceholder: "Talebinizi yazin...",
      send: "Gonder",
      sending: "Gonderiliyor...",
      sentTitle: "Mesaj gonderildi",
      sentBody: "Mesajiniz yoneticiye gonderildi.",
      tooShort: "Mesajiniz cok kisa.",
      hint: "Mesajiniz kaydedilir ve yonetici tarafindan gorulur.",
    },
    drawer: {
      roleAdmin: "Yonetici",
      roleUser: "Kullanici",
      guest: "Kullanici",
      languageTitle: "Dil",
      signOut: "Cikis yap",
      tagline: "Akilli sulama yonetimi",
    },
  },
  
};

function deepMerge(base, override) {
  const result = { ...base };
  for (const key of Object.keys(override || {})) {
    if (
      typeof override[key] === "object" &&
      override[key] !== null &&
      !Array.isArray(override[key]) &&
      typeof base[key] === "object" &&
      base[key] !== null
    ) {
      result[key] = deepMerge(base[key], override[key]);
    } else {
      result[key] = override[key];
    }
  }
  return result;
}

const TRANSLATIONS = SUPPORTED_LANGUAGES.reduce((accumulator, languageCode) => {
  accumulator[languageCode] = deepMerge(
    baseTranslations[languageCode] || {},
    AUTH_TRANSLATIONS[languageCode] || {}
  );
  return accumulator;
}, {});

const LanguageContext = createContext(null);

function getValueByPath(object, path) {
  return path.split(".").reduce((accumulator, key) => accumulator?.[key], object);
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(FALLBACK_LANGUAGE);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadLanguage() {
      try {
        const storedLanguage = await AsyncStorage.getItem(LANGUAGE_STORAGE_KEY);
        if (storedLanguage && SUPPORTED_LANGUAGES.includes(storedLanguage)) {
          setLanguageState(storedLanguage);
        }
      } catch (error) {
        console.warn("Failed to load language:", error);
      } finally {
        setIsLoading(false);
      }
    }

    loadLanguage();
  }, []);

  const setLanguage = useCallback(async (nextLanguage) => {
    if (!SUPPORTED_LANGUAGES.includes(nextLanguage)) {
      return;
    }

    setLanguageState(nextLanguage);
    try {
      await AsyncStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    } catch (error) {
      console.warn("Failed to save language:", error);
    }
  }, []);

  const value = useMemo(() => {
    const t = (key) => {
      const currentValue = getValueByPath(TRANSLATIONS[language], key);
      if (currentValue != null) {
        return currentValue;
      }

      const fallbackValue = getValueByPath(TRANSLATIONS[FALLBACK_LANGUAGE], key);
      return fallbackValue ?? key;
    };

    return {
      language,
      isRTL: language === "ar",
      isLoading,
      setLanguage,
      changeLanguage: setLanguage,
      t,
    };
  }, [isLoading, language, setLanguage]);

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
